CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS system_controls (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton), paused boolean NOT NULL DEFAULT false,
  killed boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), updated_by text NOT NULL DEFAULT 'migration'
);
INSERT INTO system_controls (singleton) VALUES (true) ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), external_id text UNIQUE NOT NULL, role text NOT NULL CHECK (role IN ('owner','agent')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ventures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, thesis text NOT NULL, target_user text NOT NULL, problem text NOT NULL, offer text NOT NULL, revenue_model text NOT NULL, distribution_strategy text NOT NULL, stage text NOT NULL DEFAULT 'research', capital_allocated_minor bigint NOT NULL DEFAULT 0 CHECK (capital_allocated_minor >= 0), evidence jsonb NOT NULL DEFAULT '[]', risks jsonb NOT NULL DEFAULT '[]', next_milestone text, kill_criteria text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS opportunities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_problem text NOT NULL, target_market text NOT NULL, evidence jsonb NOT NULL DEFAULT '[]', competitors jsonb NOT NULL DEFAULT '[]', distribution_path text NOT NULL, monetization_path text NOT NULL, build_effort text NOT NULL, time_to_revenue text NOT NULL, capital_required_minor bigint NOT NULL DEFAULT 0, reusability integer CHECK (reusability BETWEEN 0 AND 100), strategic_fit integer CHECK (strategic_fit BETWEEN 0 AND 100), expected_value numeric, confidence integer CHECK (confidence BETWEEN 0 AND 100), risks jsonb NOT NULL DEFAULT '[]', decision_status text NOT NULL DEFAULT 'under_consideration', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS objectives (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), statement text NOT NULL, status text NOT NULL DEFAULT 'active', expected_value numeric, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), venture_id uuid REFERENCES ventures(id), objective_id uuid REFERENCES objectives(id), title text NOT NULL, status text NOT NULL CHECK (status IN ('backlog','ready','in_progress','waiting','owner_blocked','validation','completed','abandoned')), priority integer NOT NULL DEFAULT 0, expected_value numeric, cost_estimate_minor bigint, decision_or_hypothesis text, completion_evidence text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS experiments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), venture_id uuid REFERENCES ventures(id), hypothesis text NOT NULL, target_customer text NOT NULL, method text NOT NULL, budget_minor bigint NOT NULL DEFAULT 0 CHECK (budget_minor >= 0), start_at timestamptz, review_at timestamptz, success_metric text NOT NULL, failure_metric text NOT NULL, stop_loss_minor bigint NOT NULL DEFAULT 0, actual_result text, lesson text, follow_up_decision text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), statement text NOT NULL, context text NOT NULL, options jsonb NOT NULL, evidence jsonb NOT NULL, selected_option text NOT NULL, rejected_options jsonb NOT NULL DEFAULT '[]', expected_result text, confidence integer CHECK (confidence BETWEEN 0 AND 100), cost_minor bigint, risk text, review_at timestamptz, actual_outcome text, lesson text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), action_type text NOT NULL, requested_action text NOT NULL, reason text NOT NULL, cost_minor bigint NOT NULL DEFAULT 0, currency char(3) NOT NULL DEFAULT 'INR', risk text NOT NULL, alternatives jsonb NOT NULL DEFAULT '[]', recommendation text NOT NULL, idempotency_key text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','modified','expired')), expires_at timestamptz NOT NULL, decided_at timestamptz, decided_by text, decision_note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS financial_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, currency char(3) NOT NULL, account_type text NOT NULL CHECK (account_type IN ('contribution','operating','reserve','revenue','expense','fee','refund','tax')), locked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ledger_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), transaction_id text UNIQUE NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), entry_type text NOT NULL CHECK (entry_type IN ('contribution','expense','revenue','refund','fee','tax_reserve','adjustment','reversal','reservation')), currency char(3) NOT NULL, gross_minor bigint NOT NULL, fees_minor bigint NOT NULL DEFAULT 0, tax_minor bigint NOT NULL DEFAULT 0, net_minor bigint NOT NULL, counterparty text NOT NULL, venture_id uuid REFERENCES ventures(id), experiment_id uuid REFERENCES experiments(id), payment_status text NOT NULL CHECK(payment_status IN ('pending','settled','failed','reversed')), provider_reference text, evidence_uri text, idempotency_key text UNIQUE NOT NULL, reconciliation_status text NOT NULL DEFAULT 'unreconciled', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS leads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source text NOT NULL, qualification text NOT NULL, contact_status text NOT NULL DEFAULT 'draft', consent_basis text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS customers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), external_ref text UNIQUE, display_name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_id uuid REFERENCES customers(id), status text NOT NULL DEFAULT 'draft', amount_minor bigint NOT NULL, currency char(3) NOT NULL, provider_reference text UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid REFERENCES invoices(id), status text NOT NULL, provider_reference text UNIQUE NOT NULL, amount_minor bigint NOT NULL, currency char(3) NOT NULL, webhook_idempotency_key text UNIQUE NOT NULL, verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, purpose text NOT NULL, action_kind text NOT NULL DEFAULT 'job', schedule text, payload jsonb NOT NULL DEFAULT '{}', idempotency_key text UNIQUE NOT NULL, status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','completed','dead_letter','cancelled')), attempts integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 3 CHECK(max_attempts BETWEEN 1 AND 10), lease_until timestamptz, next_run_at timestamptz NOT NULL DEFAULT now(), last_error text, related_venture_id uuid REFERENCES ventures(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS job_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid NOT NULL REFERENCES jobs(id), status text NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz, duration_ms integer, output jsonb, error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS artifacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, uri text NOT NULL, checksum text, venture_id uuid REFERENCES ventures(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memory_references (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id text NOT NULL, agent_id text, venture_id uuid, scope_key text NOT NULL, category text NOT NULL, epistemic_type text NOT NULL CHECK(epistemic_type IN ('fact','inference','hypothesis','instruction','lesson')), content text NOT NULL, source_uri text, confidence integer CHECK(confidence BETWEEN 0 AND 100), sensitivity text NOT NULL DEFAULT 'internal', verified_at timestamptz, review_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS memory_references_scope_idx ON memory_references(owner_id, scope_key, created_at DESC);
CREATE TABLE IF NOT EXISTS incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), severity text NOT NULL, status text NOT NULL DEFAULT 'open', summary text NOT NULL, evidence jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, occurred_at timestamptz NOT NULL DEFAULT now(), actor_type text NOT NULL, actor_id text, event_type text NOT NULL, entity_type text NOT NULL, entity_id text, correlation_id uuid, payload jsonb NOT NULL DEFAULT '{}');

CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'append-only table: % cannot be changed', TG_TABLE_NAME; END; $$;
DROP TRIGGER IF EXISTS ledger_entries_immutable ON ledger_entries;
CREATE TRIGGER ledger_entries_immutable BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION reject_mutation();
DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events;
CREATE TRIGGER audit_events_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_mutation();
