import { claimAuthorizedEffect, recordExternalResult } from './effects.ts';

export class PayPalError extends Error { readonly code: string; constructor(code: string) { super(code); this.code = code; } }
const apiBase = () => process.env.PAYPAL_ENVIRONMENT === 'live' ? 'https://api-m.paypal.com' : 'https://api-m.sandbox.paypal.com';
function credentials() { const clientId=process.env.PAYPAL_CLIENT_ID, secret=process.env.PAYPAL_SECRET; if(!clientId || !secret) throw new PayPalError('paypal_not_configured'); return {clientId,secret}; }
async function accessToken() { const {clientId,secret}=credentials(); const auth=Buffer.from(`${clientId}:${secret}`).toString('base64'); const r=await fetch(`${apiBase()}/v1/oauth2/token`,{method:'POST',headers:{authorization:`Basic ${auth}`,'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',signal:AbortSignal.timeout(10_000)}); if(!r.ok) throw new PayPalError('paypal_authentication_failed'); const body=await r.json() as {access_token?:string}; if(!body.access_token) throw new PayPalError('paypal_authentication_failed'); return body.access_token; }
async function paypal(path:string, method:string, body?:unknown, extra:Record<string,string>={}) { const token=await accessToken(); const r=await fetch(`${apiBase()}${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...extra},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body),signal:AbortSignal.timeout(15_000)}); const result=await r.json().catch(()=>({})); if(!r.ok) throw new PayPalError(`paypal_${r.status}`); return result as any; }
export class PayPalService {
  private database: any;
  constructor(database:any) { this.database = database; }
  status() { return {configured:Boolean(process.env.PAYPAL_CLIENT_ID && process.env.PAYPAL_SECRET), environment:process.env.PAYPAL_ENVIRONMENT === 'live' ? 'live' : 'sandbox', webhook_verification_configured:Boolean(process.env.PAYPAL_WEBHOOK_ID)}; }
  async createOrder(input:any) { const effectId=String(input.effect_id??''); const amount=String(input.amount??''); const currency=String(input.currency??'USD').toUpperCase(); if(!/^[A-Z]{3}$/.test(currency)||!/^(0|[1-9]\d{0,9})(\.\d{1,2})?$/.test(amount)) throw new PayPalError('invalid_amount'); const client=await this.database.connect(); try { await client.query('BEGIN'); if(!await claimAuthorizedEffect(client,effectId,'payment')) throw new PayPalError('effect_authorization_required_or_consumed'); const order=await paypal('/v2/checkout/orders','POST',{intent:'CAPTURE',purchase_units:[{reference_id:String(input.reference_id??effectId).slice(0,127),description:String(input.description??'Goofy Agent OS payment').slice(0,127),amount:{currency_code:currency,value:amount}}]},{'PayPal-Request-Id':`goofy-${effectId}`}); const approval=order.links?.find((link:any)=>link.rel==='approve')?.href; if(!order.id||!approval) throw new PayPalError('paypal_order_response_invalid'); const minor=Math.round(Number(amount)*100); await client.query(`INSERT INTO payments(status,provider_reference,amount_minor,currency,webhook_idempotency_key,created_at) VALUES('pending',$1,$2,$3,$4,now()) ON CONFLICT(provider_reference) DO NOTHING`,[order.id,minor,currency,`paypal-order:${order.id}`]); await recordExternalResult(client,effectId,{outcome:'succeeded',receipt:{provider:'paypal',order_id:order.id,approval_url:approval}}); await client.query(`INSERT INTO audit_events(actor_type,actor_id,event_type,entity_type,entity_id,payload) VALUES('agent','goofy-runtime','paypal_order_created','payment',$1,$2)`,[order.id,JSON.stringify({effect_id:effectId,currency,amount})]); await client.query('COMMIT'); return {id:order.id,status:order.status,approval_url:approval}; } catch(e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async handleWebhook(headers:Record<string, string | string[] | undefined>, rawEvent:string) { const webhookId=process.env.PAYPAL_WEBHOOK_ID; if(!webhookId) throw new PayPalError('paypal_webhook_not_configured'); let event:any; try { event=JSON.parse(rawEvent); } catch { throw new PayPalError('paypal_webhook_invalid_json'); } const header=(name:string)=>Array.isArray(headers[name])?headers[name][0]:headers[name]; const envelope=JSON.stringify({auth_algo:header('paypal-auth-algo'),cert_url:header('paypal-cert-url'),transmission_id:header('paypal-transmission-id'),transmission_sig:header('paypal-transmission-sig'),transmission_time:header('paypal-transmission-time'),webhook_id:webhookId}).replace(/}$/,`,"webhook_event":${rawEvent}}`); const verification=await paypal('/v1/notifications/verify-webhook-signature','POST',envelope); if(verification.verification_status!=='SUCCESS') throw new PayPalError('paypal_webhook_signature_invalid'); const eventId=String(event.id??''); const reference=String(event.resource?.supplementary_data?.related_ids?.order_id ?? event.resource?.id ?? ''); if(!eventId||!reference) throw new PayPalError('paypal_webhook_invalid'); const status=event.event_type==='PAYMENT.CAPTURE.COMPLETED'?'settled':event.event_type?.includes('DENIED')||event.event_type?.includes('FAILED')?'failed':'pending'; const result=await this.database.query(`UPDATE payments SET status=$2,verified_at=now() WHERE provider_reference=$1 AND webhook_idempotency_key<>$3 RETURNING id`,[reference,status,eventId]); if(result.rowCount) await this.database.query(`UPDATE payments SET webhook_idempotency_key=$2 WHERE provider_reference=$1`,[reference,eventId]); await this.database.query(`INSERT INTO audit_events(actor_type,actor_id,event_type,entity_type,entity_id,payload) VALUES('system','paypal-webhook','paypal_webhook_verified','payment',$1,$2)`,[reference,JSON.stringify({event_id:eventId,event_type:event.event_type,status})]); return {accepted:true,status}; }
}
