function escapeHtml(value: unknown) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!)); }

export function renderRevenuePathsPage(csrfToken = '') {
  const csrf = escapeHtml(csrfToken);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="${csrf}"><title>Revenue Paths · Goofy Agent OS</title><style>
:root{color-scheme:dark;--bg:#101514;--panel:#161d1b;--line:#2c3833;--text:#e8eeeb;--muted:#9aa8a1;--accent:#65bd91;--warn:#f0c674}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px ui-sans-serif,system-ui,sans-serif}main{max-width:1480px;margin:auto;padding:28px 34px 48px}.eyebrow{color:var(--accent);font-size:11px;font-weight:750;letter-spacing:.1em;text-transform:uppercase}h1{margin:5px 0;font-size:28px;letter-spacing:-.04em}.description{max-width:70ch;color:var(--muted);line-height:1.5}.toolbar{display:flex;flex-wrap:wrap;gap:9px;margin:22px 0 16px}.toolbar label{display:grid;gap:6px;color:var(--muted);font-size:12px}.toolbar input,.toolbar select{min-width:150px;padding:9px;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:var(--text)}.workspace{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(0,1.6fr);gap:16px}.panel{min-width:0;padding:18px;border:1px solid var(--line);border-radius:10px;background:var(--panel)}.panel h2{margin:0 0 5px;font-size:15px}.hint{margin:0 0 16px;color:var(--muted);font-size:12px}.tree{display:grid;gap:3px}.tree button{display:grid;grid-template-columns:18px minmax(0,1fr) auto;gap:8px;width:100%;padding:9px 8px;border:0;border-radius:7px;background:transparent;color:var(--text);text-align:left;cursor:pointer}.tree button:hover,.tree button[aria-current=true]{background:#202a26}.tree .indent-1{padding-left:25px}.tree .indent-2{padding-left:42px}.tree .indent-3{padding-left:59px}.tree .name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tag{padding:3px 7px;border:1px solid var(--line);border-radius:99px;color:var(--muted);font-size:11px;white-space:nowrap}.tag.active{border-color:#3b7258;color:#9bd7b5}.tag.proposed{border-color:#806a37;color:var(--warn)}.empty{color:var(--muted);line-height:1.5}.detail-grid{display:grid;grid-template-columns:150px minmax(0,1fr);gap:10px;margin:18px 0}.detail-grid dt{color:var(--muted)}.detail-grid dd{margin:0;overflow-wrap:anywhere}.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:18px 0}.metric{padding:12px;border:1px solid var(--line);border-radius:8px}.metric span{display:block;color:var(--muted);font-size:11px}.metric strong{display:block;margin-top:7px;font-size:18px}.handoff{padding:10px;border-left:3px solid var(--warn);background:#211f17;color:#eadcae}.error{color:#ffb7b7}@media(max-width:800px){main{padding:20px 16px}.workspace{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}}@media(max-width:480px){.toolbar{display:grid}.toolbar input,.toolbar select{width:100%}.metrics{grid-template-columns:1fr}.detail-grid{grid-template-columns:1fr}}
</style></head><body><main data-page="revenue-paths"><header><div class="eyebrow">Live PostgreSQL workspace</div><h1>Revenue Paths</h1><p class="description">A hierarchy of strategic tracks, workstreams, ventures, experiments, assets, pipeline activity, costs, and settled outcomes. Proposed paths are visible without being presented as active work.</p></header><form class="toolbar" id="filters" aria-label="Revenue path filters"><label>Status<select name="status"><option value="">All statuses</option><option>proposed</option><option>active</option><option>paused</option><option>completed</option><option>killed</option></select></label><label>Owner<select name="owner_kind"><option value="">All owners</option><option>agent</option><option>owner</option><option>joint</option></select></label><label>Stage<input name="stage" maxlength="80" placeholder="Filter stage"></label><label>Search<input name="search" maxlength="200" placeholder="Search paths"></label><button type="submit">Apply filters</button></form><section class="workspace"><section class="panel" aria-label="Revenue path hierarchy"><h2>Track hierarchy</h2><p class="hint">Select a path to inspect its thesis, evidence, handoffs, and next action.</p><div class="tree" id="trackTree"><p class="empty">Loading live paths…</p></div></section><section class="panel" id="selectedPath" aria-live="polite"><h2>Selected path</h2><p class="hint">Choose a track from the hierarchy.</p><div id="trackDetail"><p class="empty">No active revenue paths yet. Proposed paths remain visible here once they are stored in PostgreSQL.</p></div></section></section></main><script>window.__csrf=${JSON.stringify(csrf)};</script><script>${clientScript()}</script></body></html>`;
}

function clientScript() {
  return String.raw`(() => {
    const tree = document.querySelector('#trackTree'); const detail = document.querySelector('#trackDetail'); const filters = document.querySelector('#filters'); let tracks = [];
    const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const label = value => String(value ?? '').replaceAll('_',' ').replace(/\b\w/g, c => c.toUpperCase());
    const money = (value, currency) => new Intl.NumberFormat('en-IN',{style:'currency',currency}).format(Number(value || 0) / 100);
    const moneyByCurrency = (metrics, field) => Object.entries(metrics.currencyMetrics || {}).map(([currency, values]) => '<div class="metric"><span>'+escape(currency)+' '+escape(label(field))+'</span><strong>'+money(values[field],currency)+'</strong></div>').join('');
    const visible = () => { const f = Object.fromEntries(new FormData(filters).entries()); return tracks.filter(t => (!f.status || t.status === f.status) && (!f.owner_kind || t.owner_kind === f.owner_kind) && (!f.stage || t.stage.toLowerCase().includes(String(f.stage).toLowerCase())) && (!f.search || t.name.toLowerCase().includes(String(f.search).toLowerCase()))); };
    const drawTree = () => { const rows = visible(); if (!rows.length) { tree.innerHTML = '<p class="empty">No paths match these filters. Proposed paths remain visible when their status is selected.</p>'; return; } const children = new Map(); for (const t of rows) children.set(t.id, []); for (const t of rows) if (children.has(t.parent_track_id)) children.get(t.parent_track_id).push(t); const roots = rows.filter(t => !t.parent_track_id || !children.has(t.parent_track_id)); const output=[]; const walk=(t,depth)=>{ output.push('<button type="button" aria-expanded="true" aria-current="false" data-track="'+escape(t.id)+'" class="indent-'+Math.min(depth,3)+'"><span>›</span><span class="name">'+escape(t.name)+'</span><span class="tag '+(t.status === 'proposed' ? 'proposed' : 'active')+'">'+escape(label(t.status))+'</span></button>'); for(const child of children.get(t.id)||[]) walk(child,depth+1); }; roots.forEach(t=>walk(t,0)); tree.innerHTML=output.join(''); tree.querySelectorAll('[data-track]').forEach(button=>button.addEventListener('click',()=>select(button.dataset.track))); };
    async function select(id) { tree.querySelectorAll('[data-track]').forEach(button=>button.setAttribute('aria-current',button.dataset.track===id?'true':'false')); try { const t=await fetch('/api/revenue-tracks/'+encodeURIComponent(id),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Unable to load selected path');return r.json()}); const m=t.metrics||{}; const currencyMetrics=Object.keys(m.currencyMetrics||{}).length ? '<div class="metrics">'+moneyByCurrency(m,'settledRevenueMinor')+moneyByCurrency(m,'settledExpenseMinor')+moneyByCurrency(m,'settledNetMinor')+'</div>' : '<div class="metrics"><div class="metric"><span>Settled revenue</span><strong data-metric="settled-revenue">'+money(m.settledRevenueMinor,'INR')+'</strong></div><div class="metric"><span>Settled expense</span><strong>'+money(m.settledExpenseMinor,'INR')+'</strong></div><div class="metric"><span>Settled net</span><strong>'+money(m.settledNetMinor,'INR')+'</strong></div></div>'; detail.innerHTML='<h3>'+escape(t.name)+'</h3><dl class="detail-grid"><dt>Status</dt><dd><span class="tag '+(t.status==='proposed'?'proposed':'active')+'">'+escape(label(t.status))+'</span></dd><dt>Owner</dt><dd>'+escape(label(t.owner_kind))+'</dd><dt>Stage</dt><dd>'+escape(t.stage)+'</dd><dt>Thesis</dt><dd>'+escape(t.strategy||'Not recorded')+'</dd><dt>Target customer</dt><dd>'+escape(t.target_customer||'Not recorded')+'</dd><dt>Monetization</dt><dd>'+escape(t.monetization_model||'Not recorded')+'</dd><dt>Current action</dt><dd>'+escape(t.current_action||'Not recorded')+'</dd><dt>Next action</dt><dd>'+escape(t.next_action||'Not scheduled')+'</dd></dl>'+currencyMetrics+(m.ownerHandoffCount?'<p class="handoff" data-metric="owner-handoff">'+m.ownerHandoffCount+' item(s) require owner handoff.</p>':'<p class="hint">No owner handoff items recorded.</p>'); } catch(error) { detail.innerHTML='<p class="error">'+escape(error.message)+'</p>'; } }
    async function load() { try { tracks=await fetch('/api/revenue-tracks',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Unable to load revenue paths');return r.json()}); drawTree(); if(tracks[0]) select(tracks[0].id); } catch(error) { tree.innerHTML='<p class="error">'+escape(error.message)+'</p>'; } }
    filters.addEventListener('submit',event=>{event.preventDefault();drawTree()}); load();
  })();`;
}
