function escapeHtml(value: unknown) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[char]!)); }
export function renderWalletPage(csrf: string | undefined, infuraProjectId: string | undefined, status: any = {}, agentStatus: any = {}) {
  const key = JSON.stringify(infuraProjectId ?? null).replace(/</g,'\\u003c');
  const linked = status.link ? `${escapeHtml(status.link.address)} · Ethereum Mainnet` : 'No wallet linked';
  const balance = status.balance_wei === null || status.balance_wei === undefined ? 'No linked-wallet balance to display' : `${(Number(status.balance_wei) / 1e18).toFixed(6)} ETH`;
  const intents = Array.isArray(status.intents) && status.intents.length ? status.intents.map((intent: any) => `<tr><td>${escapeHtml(intent.purpose)}</td><td><code>${escapeHtml(intent.to_address)}</code><br>${(Number(intent.value_wei) / 1e18).toFixed(8)} ETH</td><td>${intent.data === '0x' ? 'Native ETH transfer' : '<strong>Raw calldata warning</strong>'}</td><td>${escapeHtml(intent.status)}</td><td>${intent.status === 'draft' ? '<span>Available after approval</span>' : ''}</td></tr>`).join('') : '<tr><td colspan="5">No transaction drafts. Link a public wallet address to begin.</td></tr>';
  const agent = agentStatus.wallet;
  const operations = Array.isArray(agentStatus.operations) && agentStatus.operations.length
    ? agentStatus.operations.map((operation: any) => `<tr><td>${escapeHtml(operation.created_at)}</td><td>${escapeHtml(operation.provider)}</td><td>${escapeHtml(operation.operation_type)}</td><td>${escapeHtml(operation.outcome)}${operation.error_code ? `<br><small>${escapeHtml(operation.error_code)}</small>` : ''}</td><td><code>${escapeHtml(operation.message_hash)}</code></td></tr>`).join('')
    : '<tr><td colspan="5">No dedicated-wallet activity recorded.</td></tr>';
  const agentPanel = agent
    ? `<section><h2>Dedicated Goofy wallet</h2><p class="notice">Autonomous authority is bounded by the policy shown here. Secret material is ${escapeHtml(agentStatus.key_exposure)} and never returned by this page.</p><div class="grid"><div><strong>Public address</strong><p><code>${escapeHtml(agent.address)}</code></p></div><div><strong>Status / chains</strong><p>${escapeHtml(agent.status)} · ${escapeHtml((agent.allowed_chain_ids ?? []).join(', '))}</p></div><div><strong>Base ETH</strong><p>${agentStatus.balances?.eth_wei == null ? 'Unavailable' : `${(Number(agentStatus.balances.eth_wei) / 1e18).toFixed(8)} ETH`}</p></div><div><strong>Base USDC</strong><p>${agentStatus.balances?.usdc_atomic == null ? 'Unavailable' : `${(Number(agentStatus.balances.usdc_atomic) / 1e6).toFixed(2)} USDC`}</p></div></div><p><strong>Policy</strong><br><code>${escapeHtml(JSON.stringify(agent.policy ?? {}))}</code></p><h3>Signing activity</h3><table><thead><tr><th>When</th><th>Provider</th><th>Operation</th><th>Outcome</th><th>Message hash</th></tr></thead><tbody>${operations}</tbody></table></section>`
    : '<section><h2>Dedicated Goofy wallet</h2><p>Not provisioned.</p></section>';
  return `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="${escapeHtml(csrf ?? '')}"><title>Wallet · Goofy Agent OS</title><style>body{font:14px system-ui;margin:auto;max-width:1100px;padding:34px;background:#101514;color:#e8eeeb}section{border:1px solid #2c3833;background:#161d1b;border-radius:10px;padding:18px;margin:16px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}button{padding:10px;border-radius:7px;border:1px solid #65bd91;background:#65bd91;color:#08261b;font-weight:700;cursor:pointer}code,small{overflow-wrap:anywhere;color:#9aa8a1}table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;border-top:1px solid #2c3833;vertical-align:top}.error{color:#ffb7b7}.notice{color:#f0c674}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><a href="/">← Command Centre</a><h1>Wallet operations</h1>${agentPanel}<p id="walletMessage" role="status"></p><section><h2>Owner-linked MetaMask</h2><p class="notice">MetaMask keeps the private key. A connection does not authorize spending: every write needs a durable Agent OS draft, owner approval, and a separate MetaMask confirmation.</p><div class="grid"><div><strong>Linked account</strong><p id="walletState">${linked}</p></div><div><strong>Live ETH balance</strong><p id="walletBalance">${balance}</p></div></div><button id="walletConnect">Connect or link MetaMask</button> <button id="walletRevoke">Revoke link</button></section><section><h2>Immutable transaction drafts</h2><p>Raw calldata is shown as an explicit warning. A signing attempt cannot be replayed after a browser interruption.</p><table><thead><tr><th>Purpose</th><th>Recipient / value</th><th>Call</th><th>State</th><th>Owner action</th></tr></thead><tbody id="walletIntents">${intents}</tbody></table></section><script>window.__walletConfig={infuraProjectId:${key}}</script><script type="module" src="/assets/wallet-client.js"></script>`;
}
